"""A global, reusable configuration file for Sphinx documentation."""
import os
import sys
from datetime import datetime

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), 'directives')))

html_context = {}


def setup_globals(org: str, org_name: str, repo: str, repo_name: str) -> None:
    """
    Set up global variables for the Sphinx configuration.

    Args:
        org: The GitHub organization or username.
        org_name: The display name of the organization.
        repo: The GitHub repository name.
        repo_name: The display name of the repository.
    """
    globals().update(
        {
            "org": org,
            "org_name": org_name,
            "repo": repo,
            "repo_name": repo_name,
            "blog_title": f"{org_name} • {repo_name}",
            "html_title": f"{org_name} • {repo_name}",
            "project": f"{org_name} • {repo_name}",
            "version": "",  # The short X.Y version.
            "release": "",  # The full version, including alpha/beta/rc tags.
            "copyright": f"{year}, {org_name}",
            "author": org_name,
            "blog_baseurl": f"https://{org}.github.io/{repo}",
            "html_base_url": f"https://{org}.github.io/{repo}",
            "html_baseurl": f"https://{org}.github.io/{repo}",
            "blog_authors": {"phi": ("phi ARCHITECT", None)},
        }
    )
    html_context.update(
        {
            "display_github": True,
            "github_user": org,
            "github_repo": repo,
            "github_version": "main",
            "conf_py_path": "/docsrc/",
            "org_name": org_name,
            "repo_name": repo_name,
        }
    )


year = datetime.now().year


# -- Sphinx Options -----------------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    #  "sphinx.ext.autodoc",
    #  "sphinx.ext.autosummary",
    "sphinx.ext.extlinks",
    "sphinx.ext.intersphinx",
    "sphinx.ext.githubpages",
    "sphinx.ext.graphviz",
    "sphinx.ext.mathjax",
    "sphinx.ext.todo",
    "sphinx.ext.viewcode",
    "sphinxcontrib.youtube",
    #  "sphinxcontrib.bibtex",
    "myst_parser",
    "sphinx_revealjs",
    "sphinx_revealjs.ext.footnotes",
    #  "sphinx_revealjs.ext.screenshot",
    #  "sphinxcontrib.budoux",
    #  "sphinxcontrib.gtagjs",
    #  "sphinxcontrib.oembed",
    "sphinxext.opengraph",
    "sphinx_carousel.carousel",
    "sphinxcontrib.jquery",
    "photon_platform.publish.directives.collection",
    "autoapi.extension",
]

# autosummary_generate = True

# AutoAPI options
autoapi_dirs = ['../src']
autoapi_options = [
    'members',
    'undoc-members',
    'show-inheritance',
    'show-module-summary',
    'special-members',
]
autoapi_root = 'modules/api'

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
source_suffix = {
    ".rst": "restructuredtext",
    ".txt": "markdown",
    ".md": "markdown",
}

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = [".archive", ".docs", "tests", "*.egg-info"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "gruvbox-dark"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.

html_theme = "photon"


# Add any paths that contain custom themes here, relative to this directory.
html_theme_path = [os.path.abspath(os.path.join(os.path.dirname(__file__), 'themes'))]

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# Output file base name for HTML help builder.
htmlhelp_basename = "help_doc"


html_theme_options = {
    "display_version": False,
    "navigation_depth": -1,
    "prev_next_buttons_location": "both",
    "collapse_navigation": False,
    "includehidden": True,
    "titles_only": False,
    "sticky_navigation": True,
}

intersphinx_mapping = {
    "python": ("https://docs.python.org/3.9", None),
    "sympy": ("https://docs.sympy.org/latest", None),
}

html_logo = "_static/logo.png"

autodoc_default_options = {
    "members": True,
    "member-order": "bysource",
    #  'special-members': '__init__',
    "undoc-members": True,
    #  'exclude-members': '__weakref__'
    "show-inheritance": True,
}

html_permalinks = True
